### ISSUE TITLE
Styling Problem with Component 'PostList'

### ISSUE THREAD

**Issue by gnujoow** [pjhjohn/jsonplaceholder-client#14]
only 5 Post are shown .

**Comment by pjhjohn** [comment]
Seems that `column` `col-3` classes wrapped by `columns` class does not support line-feeding like behavior.  

Thinking of introducing [bootstrap in sass way](https://github.com/twbs/bootstrap-sass) for grid-handling (also form-grouping)

**Comment by pjhjohn** [comment]
Changed issue title, adding label for more readability
