### ISSUE TITLE
TODO : STICKY FOOTER + minimum contents height even if contents is empty

### ISSUE THREAD

**Issue by gnujoow** [pjhjohn/jsonplaceholder-client#32]
TODO : STICKY FOOTER + minimum contents height even if contents is empty

https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/
https://css-tricks.com/couple-takes-sticky-footer/

---

ref : https://github.com/pjhjohn/jsonplaceholder-client/pull/30#issuecomment-241245861

**Comment by pjhjohn** [comment]
Possible TODO : Implement in `flex-way` for HTML5-like webpage
